; [PlatformIO Project Configuration File]
; @repository t4rxnn-devel/hil-pneumatic-controller
; @details Configuration manifest for Teensy 4.1 target board running the HIL pneumatic controller.

[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = 
    -O3
    -Wall
    -DCORE_TEENSY
    -DUSB_SERIAL
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
monitor_speed = 500000
upload_protocol = teensy-cli
